package tghtechnology.tiendavirtual.Utils.ApisPeru.Enums;

import lombok.Getter;

public enum TipoDocumento {

	FACTURA("01"),
	BOLETA_DE_VENTA("03"),
	NOTA_DE_CREDITO("07"),
	NOTA_DE_DEBITO("08"),
	GUIA_DE_REMISION_REMITENTE("09"),
	TICKET_MAQUINA_REGISTRADORA("12"),
	DOCUMENTO_EMITIDO_POR_BANCOS("13"),
	RECIBO_SERVICIOS_PUBLICOS("14"),
	BOLETO_DE_VIAJE("16"),
	DOCUMENTO_EMITIDO_POR_AFP("18"),
	COMPROBANTE_DE_RETENCION("20"),
	GUIA_DE_REMISION_TRANSPORTISTA("31"),
	COMPROBANTE_DE_PERCEPCION("40"),
	COMPROBANTE_DE_PERCEPCION_VENTA_INTERNA("41"),
	COMPROBANTE_DE_PAGO_SEAE("56"),
	GUIA_DE_REMISION_REMITENTE_COMPLEMENTARIA("71"),
	GUIA_DE_REMISION_TRANSPORTISTA_COMPLEMENTARIA("72")
	;
	
	@Getter
	private String label;
	
	TipoDocumento(String label) {
		this.label = label;
	}
}
