package tghtechnology.chozaazul.Utils.ApisPeru.Enums;

import lombok.Getter;

/**
 * Tipos de cargo (Incluye descuentos y cargos extra)
 */
public enum TipoCargo {

	
	DESC_AFECTA_BASE_IMPONIBLE_IGV_IVAP("00"),
	DESC_NO_AFECTA_BASE_IMPONIBLE_IGV_IVAP("01"),
	DESC_GLOBAL_AFECTA_BASE_IMPONIBLE_IGV_IVAP("02"),
	DESC_GLOBAL_NO_AFECTA_BASE_IMPONIBLE_IGV_IVAP("03"),
	DESC_GLOBAL_POR_ANTICIPO_GRAVADO("04"),
	DESC_DESC_GLOBAL_POR_ANTICIPO_EXONERADO("05"),
	DESC_GLOBAL_POR_ANTICIPO_INAFECTO("06"),
	FISE("45"),
	RECARGO_AL_CONSUMO_YO_PROPINAS("46"),
	CARGO_AFECTA_BASE_IMPONIBLE_IGV_IVAP("47"),
	CARGO_NO_AFECTA_BASE_IMPONIBLE_IGV_IVAP("48"),
	CARGO_GLOBAL_AFECTA_BASE_IMPONIBLE_IGV_IVAP("49"),
	CARGO_GLOBAL_NO_AFECTA_BASE_IMPONIBLE_IGV_IVAP("50"),
	PERCEPCION_VENTA_INTERNA("51"),
	PERCEPCION_COMBUSTIBLE("52"),
	PERCEPCION_CON_TASA_ESPECIAL("53")
	;
	
	
	@Getter
	private String label;
	
	TipoCargo(String label) {
		this.label = label;
	}
}
